126 switching out fire picker
focus-browser/browser pull request #128
Opened 2022-10-21 23:18 UTC by PressJump

Fire-picker at this point of time is dead and needs for a rewriting in terms of injection and optimization, more information can be found at the issue https://github.com/pulse-browser/fire-picker/issues/3 . In the state of feature freeze it is a good idea to replace it with https://github.com/pulse-browser/firefox-qr-generator an in house productivity extension.

Fixes #126

2022-10-22 09:43 UTC, trickypr requested changes
There are some issues with the addon.
1. Does not respect QRCode safe areas (should be [4+ modules](https://www.qrcode.com/en/howto/code.html))
2. Does not scale with browser / wm (set `layout.css.devPixelsPerPx` to 3 to exaggerate effect)

There are a bunch of UI things that need to be cleaned up (e,g, unreadable icons at small scales), but I need to go and do a UI pass soon anyway, so I will let them pass

2022-10-22 09:50 UTC, PressJump commented
> There are some issues with the addon.
> 
>     1. Does not respect QRCode safe areas (should be [4+ modules](https://www.qrcode.com/en/howto/code.html))
> 
>     2. Does not scale with browser / wm (set `layout.css.devPixelsPerPx` to 3 to exaggerate effect)
> 
> 
> There are a bunch of UI things that need to be cleaned up (e,g, unreadable icons at small scales), but I need to go and do a UI pass soon anyway, so I will let them pass

Will make the listed appropriate changes on the extension from safe spaces and responsive sizing.

2022-10-25 05:20 UTC, trickypr commented
Depends on pulse-browser/firefox-qr-generator#2

2022-10-25 23:22 UTC, trickypr requested changes

2022-10-25 23:22 UTC, trickypr commented on gluon.json
> +      "version": "v0.0.0",
Why are we still on v0.0.0? That is not how versioning works.

2022-10-31 03:46 UTC, trickypr approved these changes

2022-10-31 03:47 UTC, merged